// Each module = one Firestore collection. perm: rw (full) | r (read) | own (student manages own records)
const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const CLS = { name: 'classId', label: 'Class', type: 'select', ref: 'classes', required: true };
const STU = { name: 'studentId', label: 'Student', type: 'select', ref: 'students', required: true, roles: ['admin', 'faculty'] };
export const MODULES = [
  { key: 'classes', title: 'Classes', icon: 'bi-building', scope: 'none', cols: ['name', 'section'],
    fields: [{ name: 'name', label: 'Class name', required: true }, { name: 'section', label: 'Section / Year' }],
    perm: { admin: 'rw', faculty: 'r', student: 'r' } },
  { key: 'faculty', title: 'Faculty', icon: 'bi-person-workspace', scope: 'none', cols: ['name', 'email', 'subject', 'classIds'],
    fields: [{ name: 'name', label: 'Full name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true, createOnly: true },
      { name: 'password', label: 'Temporary password', type: 'password', required: true, createOnly: true, transient: true },
      { name: 'subject', label: 'Subject' }, { name: 'classIds', label: 'Classes taught', type: 'multiselect', ref: 'classes' }],
    perm: { admin: 'rw' } },
  { key: 'students', title: 'Students', icon: 'bi-people', scope: 'class', noCreate: true, cols: ['name', 'rollNo', 'classId', 'email'],
    fields: [{ name: 'name', label: 'Name', required: true }, { name: 'rollNo', label: 'Roll number', required: true }, CLS],
    perm: { admin: 'rw', faculty: 'r' } },
  { key: 'subjects', title: 'Subjects', icon: 'bi-journal-bookmark', scope: 'class', cols: ['name', 'code', 'classId'],
    fields: [{ name: 'name', label: 'Subject name', required: true }, { name: 'code', label: 'Code' }, CLS],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'notes', title: 'Notes', icon: 'bi-file-earmark-text', scope: 'class', cols: ['title', 'subject', 'classId', 'link'],
    fields: [{ name: 'title', label: 'Title', required: true }, { name: 'subject', label: 'Subject', required: true }, CLS,
      { name: 'link', label: 'Google Drive link', type: 'url', required: true }, { name: 'description', label: 'Detailed description', type: 'textarea' }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'announcements', title: 'Announcements', icon: 'bi-megaphone', scope: 'class', cols: ['title', 'message', 'classId'],
    fields: [{ name: 'title', label: 'Title', required: true }, CLS, { name: 'message', label: 'Message', type: 'textarea', required: true }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'assignments', title: 'Assignments', icon: 'bi-clipboard-check', scope: 'class', cols: ['title', 'subject', 'classId', 'deadline'],
    fields: [{ name: 'title', label: 'Title', required: true }, { name: 'subject', label: 'Subject', required: true }, CLS,
      { name: 'deadline', label: 'Deadline', type: 'date', required: true }, { name: 'description', label: 'Instructions', type: 'textarea' }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'timetable', title: 'Timetable', icon: 'bi-calendar3', scope: 'class', cols: ['day', 'startTime', 'endTime', 'subject', 'room', 'classId'],
    fields: [CLS, { name: 'day', label: 'Day', type: 'select', options: DAYS, required: true }, { name: 'startTime', label: 'Start', type: 'time', required: true },
      { name: 'endTime', label: 'End', type: 'time', required: true }, { name: 'subject', label: 'Subject', required: true }, { name: 'room', label: 'Room' }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'attendance', title: 'Attendance', icon: 'bi-check2-square', scope: 'student', derive: true, cols: ['studentId', 'date', 'status', 'classId'],
    fields: [STU, { name: 'date', label: 'Date', type: 'date', required: true }, { name: 'status', label: 'Status', type: 'select', options: ['Present', 'Absent'], required: true }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'exams', title: 'Exams & Quizzes', icon: 'bi-pencil-square', scope: 'class', cols: ['title', 'subject', 'date', 'duration', 'classId'],
    fields: [{ name: 'title', label: 'Title', required: true }, { name: 'subject', label: 'Subject', required: true }, CLS,
      { name: 'date', label: 'Date', type: 'date', required: true }, { name: 'duration', label: 'Duration (minutes)', type: 'number' },
      { name: 'link', label: 'Quiz link (optional)', type: 'url' }, { name: 'description', label: 'Syllabus / instructions', type: 'textarea' }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'marks', title: 'Marks & Results', icon: 'bi-bar-chart-line', scope: 'student', derive: true, cols: ['studentId', 'subject', 'examTitle', 'score', 'total'],
    fields: [STU, { name: 'subject', label: 'Subject', required: true }, { name: 'examTitle', label: 'Exam', required: true },
      { name: 'score', label: 'Score', type: 'number', required: true }, { name: 'total', label: 'Out of', type: 'number', required: true }],
    perm: { admin: 'rw', faculty: 'rw', student: 'r' } },
  { key: 'doubts', title: 'Doubts', icon: 'bi-chat-dots', scope: 'student', cols: ['studentName', 'subject', 'question', 'answer'],
    fields: [{ name: 'subject', label: 'Subject', required: true }, { name: 'question', label: 'Your doubt', type: 'textarea', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', roles: ['admin', 'faculty'] }],
    perm: { admin: 'rw', faculty: 'rw', student: 'own' } },
  { key: 'tasks', title: 'Study Tasks', icon: 'bi-list-task', scope: 'student', cols: ['title', 'due', 'status'],
    fields: [{ name: 'title', label: 'Task', required: true }, { name: 'due', label: 'Due date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Pending', 'Done'], required: true }],
    perm: { student: 'own' } }
];
